# Use Node.js Alpine image
FROM node:18-alpine

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and install dependencies
COPY bakery-api-service/package*.json ./
RUN npm install --production

# Copy app source code
COPY bakery-api-service/ .

# Expose port
EXPOSE 3001

# Start the app
CMD ["node", "index.js"]
